<!-- DataTables CSS -->

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Favoritos</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <!-- /.panel-heading -->
                <!--<div class="panel-body">-->
                <div class="tabs-content">
                    <div class="tabs-menu clearfix">
                        <ul>
                            <li><a class="active-tab-menu" href="#" data-tab="tab1">Tarefas(<?php echo $view_menu["t_tarefas"] ?>)</a></li>
                            <li><a href="#" data-tab="tab2">Relatórios(<?php echo $view_menu["t_relatorios"] ?>)</a></li>
                            <li><a href="#" data-tab="tab3">Consultas(<?php echo $view_menu["t_consultas"] ?>)</a></li>
                            <li><a href="#" data-tab="tab4">Cadastros(<?php echo $view_menu["t_cadastros"] ?>)</a></li>
                        </ul>
                    </div> <!-- tabs-menu -->

                    <div class="tab1 tabs first-tab">
                        <div class="dataTable_wrapper">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="tarefas">
                                <thead>
                                    <tr>
                                        <th>Aplicação</th>
                                        <th>Favorito</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php echo $view_menu["tarefas"] ?>
                                </tbody>
                            </table>
                        </div>
                    </div> <!-- .tab1 -->

                    <div class="tab2 tabs">
                        <div class="dataTable_wrapper">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="relatorios">
                                <thead>
                                    <tr>
                                        <th>Aplicação</th>
                                        <th>Favorito</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php echo $view_menu["relatorios"] ?>
                                </tbody>
                            </table>
                        </div>
                    </div> <!-- .tab2 -->

                    <div class="tab3 tabs">
                        <div class="dataTable_wrapper">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="consultas">
                                <thead>
                                    <tr>
                                        <th>Aplicação</th>
                                        <th>Favorito</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php echo $view_menu["consultas"] ?>
                                </tbody>
                            </table>
                        </div>
                    </div> <!-- .tab3 -->

                    <div class="tab4 tabs">
                        <div class="dataTable_wrapper">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="cadastros">
                                <thead>
                                    <tr>
                                        <th>Aplicação</th>
                                        <th>Favorito</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php echo $view_menu["cadastros"] ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
