<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header"><?php echo $view_indicadores_quant["descricao"] ?></h1>
            <h3><?php echo $view_indicadores_sub["descricao"] ?></h3>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add_negacao" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
            </button>
            <button type="button" id="close_sub" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Voltar
            </button>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <input type="hidden" id="txtID" value="<?php echo $view_indicadores_quant["id"] ?>" />
    <input type="hidden" id="txtIdSub" value="<?php echo $view_indicadores_sub["id"] ?>" />
    <div class="row">
        <div class="col-lg-12">

            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="empresas_listas">
                    <thead>
                        <tr>
                            <th style="width: 7%">ID</th>
                            <th>Descrição</th>
                            <th style="width: 5px"></th>
                            <th style="width: 5px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_indicadores_negacao as $un => $t) {

                            echo '
                                    <tr>
                                        <td>' . $t["id"] . '</td>
                                        <td>' . $t["descricao"] . '</td>
                                        <td><a href="#" onclick="javascript:edita_negacao(' . $t["id"] . ');"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                                        <td><a href="#" onclick="javascript:remove_negacao(' . $t["id"] . ');"><i class="fa fa-remove fa-2x"></i></a></td>
                                    </tr>
                             ';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ModalRemoveNegacao" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo TITLE ?></h4>
            </div>
            <div class="modal-body">
                <p>Tem certeza de que deseja remover esse registro?!</p>
                <button type="button" class="btn btn-danger" id="remover_negacao" data-dismiss="modal">Sim! Sei o que estou fazendo</button>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo WEBFILES ?>js/indicadores_quant_tipo.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>
