<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-11" >
            <h1 class="page-header">Planos de Ação Pendentes</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="avaliacao_lista">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Cargo</th>
                            <th>Avaliador</th>
                            <th>Data Avaliação</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_funcionarios as $value) {
                            echo '
                                    <tr class="tr_table" onclick="abre_plano(this)" id_avaliacao="' . $value["id"] . '">
                                        <td>' . $value["pessoa"] . '</td>
                                        <td>' . $value["descricao_formatado"] . '</td>
                                        <td>' . $value["avaliador"] . '</td>
                                        <td>' . $value["data_avaliacao"] . '</td>
                                    </tr>
                             ';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script src="<?php echo WEBFILES ?>js/pdi.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/pdi.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>
