<link href="<?php echo WEBFILES ?>css/parametros.css" rel="stylesheet" type="text/css">
<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">Menu</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="save" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Nome*</label>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtNome" id="txtNome" maxlength="50" required>
                        </div>
                        <div class="form-group">
                            <label>Posição*</label>
                            <input class="form-control" type="number" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtOrdem" id="txtOrdem" maxlength="50" value="1" required>
                        </div>
                        <div class="form-group">
                            <label>Link</label>
                            <input class="form-control" autocomplete="off" name="txtLink" id="txtLink" maxlength="50" >
                        </div>
                        <div class="form-group">
                            <label>Icone (Font Awesome)</label>
                            <input class="form-control" autocomplete="off" name="txtIcone" id="txtIcone" maxlength="50" >
                        </div>
                        <div class="form-group">
                            <label>Nome interno</label>
                            <input class="form-control" autocomplete="off" name="txtNInterno" id="txtNInterno" maxlength="50" >
                        </div>
                        <div class="form-group">
                            <label>Target</label>
                            <select class="form-control" autocomplete="off" name="selTarget" id="selTarget" >
                                <option selected value="">Null</option>
                                <option value="_blank">_blank</option>
                                <option value="_self">_self</option>
                                <option value="_parent">_parent</option>
                                <option value="_top">_top</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                Estrutura
                            </div>
                            <div class="panel-body">
                                <div id="tree">
                                    <ul class="teste">
                                        <li class=""> <input type="radio" required name="radRoot" id="radRoot" checked value="0"><span>Root</span>
                                    </ul>
                                    <?php print_r($view_menu); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal fade" id="loading" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo TITLE ?></h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <img alt="loading" title="loading" src="<?php echo WEBFILES ?>/img/loading_1.gif" />
            </div>
        </div>
    </div>
</div>
<script src="<?php echo WEBFILES ?>js/menu.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>
<script src="<?php echo WEBFILES ?>js/jquery.tree.min.js"></script>
<script type="text/javascript">
                                $(document).ready(function () {
                                    $('#tree').tree({
                                        collapsible: true,
                                        dnd: false,
                                        onCheck: {
                                            node: 'expand'
                                        },
                                        onUncheck: {
                                            node: 'collapse'
                                        },
                                    });
                                });
</script>