<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-1" >
            <h1 class="page-header">PDI</h1>
        </div>
        <div class="col-lg-7">
            <h3><?php echo $view_pdi["dados"]["nome"] ?></h3>
            <h4><?php echo $view_pdi["dados"]["cargo"] ?></h4>
        </div>
        <div class="col-lg-4 botoes_menu" >
            <button type="button" id="save" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Finalizar
            </button>

            <button type="button" id="close" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Voltar
            </button>
        </div>
    </div>
    <input type="hidden" id="txtId" value="<?php echo $view_pdi["dados"]["id"] ?>" />
    <div class="panel panel-default">
        <div class="panel-body" >
            <div class="row">
                <div class="col-lg-12">
                    <h3>Competências</h3>
                </div>
            </div>

            <?php
            if (!count($view_pdi["indicadores_quantitativos"])) {
                echo '<h2>Colaborador sem apontamentos necessários</h2>';
            }

            foreach ($view_pdi["indicadores_quantitativos"] as $value) {
                echo '
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            ' . $value["descricao"] . '
                        </div>
                        <div class="panel-body">
                ';
                foreach ($value["indicadores"] as $value_indicadores) {
                    echo '
                        <div class="panel panel-success">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-lg-9">
                                        <b>NÃO CONFORMIDADE</b><br />
                                        ' . $value_indicadores["indicadores"] . '
                                    </div>
                                    <div class="col-lg-2">
                                        <b>ÍNDICE ALCANÇADO</b><br />
                                        ' . $value_indicadores["negacao"] . '
                                    </div>
                                    <div class="col-lg-1">
                                        <button type="button" onclick="javascript:modalPlanoAcao(' . $value_indicadores["id"] . ',1)" class="btn btn-success">
                                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Adicionar
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <table width="100%" class="table table-striped table-bordered table-hover" id="tbl' . $value_indicadores["id"] . '">
                                            <thead>
                                                <tr>
                                                    <th>Plano de Ação</th>
                                                    <th>Evidências dos Resultados/Metas</th>
                                                    <th>Matriz GUT</th>
                                                    <th>Participantes/Área</th>
                                                    <th style="width: 10px;"></th>
                                                    <th style="width: 10px;"></th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                ';
                    foreach ($value_indicadores["plano_acao"] as $value_plano_acao) {
                        echo '
                            <tr>
                                <td>' . $value_plano_acao["plano_acao"] . '</td>
                                <td>' . $value_plano_acao["evidencia"] . '</td>
                                <td>' . $value_plano_acao["gut"] . '</td>
                                <td>' . $value_plano_acao["participantes"] . '</td>
                                <td><button type="button" class="btn btn-link" onclick="javascript:edit_plano(' . $value_plano_acao["id"] . ', ' . $value_indicadores["id"] . ',1);"><i class="fa fa-pencil-square-o fa-2x"></i></button></td>
                                <td><button type="button" class="btn btn-link" onclick="javascript:remover_plano(' . $value_plano_acao["id"] . ', ' . $value_indicadores["id"] . ',1);"><i class="fa fa-trash fa-2x"></i></button></td>
                            </tr>
                        ';
                    }
                    echo'
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ';
                }

                echo'
                            </div>
                        </div>
                ';
            }
            ?>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body" >
            <div class="row">
                <div class="col-lg-12">
                    <h3>Habilidades</h3>
                </div>
            </div>
            <?php
            foreach ($view_pdi["indicadores_qualitativos"] as $key => $value) {
                echo '
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-lg-9">
                                    <b>NÃO CONFORMIDADE: ' . $value["descricao"] . '</b><br />
                                    ' . $value["avaliacao"]["descricao"] . '
                                </div>
                                <div class="col-lg-2">
                                    <b>ÍNDICE ALCANÇADO</b><br />
                                    Ordem Horizontal ' . $value["avaliacao"]["ordem_horizontal"] . ' ' . ($value["avaliacao"]["intermediario"] ? "Intermediário" : "") . '
                                </div>
                                <div class="col-lg-1">
                                    <button type="button" onclick="javascript:modalPlanoAcao(' . $value["avaliacao"]["id"] . ',2)" class="btn btn-success">
                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Adicionar
                                    </button>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body" >
                            <div class="row">
                                <div class="col-lg-12">
                                    <table width="100%" class="table table-striped table-bordered table-hover" id="tblHabilidades' . $value["avaliacao"]["id"] . '">
                                        <thead>
                                            <tr>
                                                <th>Plano de Ação</th>
                                                <th>Evidências dos Resultados/Metas</th>
                                                <th>Matriz GUT</th>
                                                <th>Participantes/Área</th>
                                                <th style="width: 10px;"></th>
                                                <th style="width: 10px;"></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        ';
                foreach ($value["plano_acao"] as $value_plano_acao) {
                    echo '
                        <tr>
                                <td>' . $value_plano_acao["plano_acao"] . '</td>
                                <td>' . $value_plano_acao["evidencia"] . '</td>
                                <td>' . $value_plano_acao["gut"] . '</td>
                                <td>' . $value_plano_acao["participantes"] . '</td>
                                <td><button type="button" class="btn btn-link" onclick="javascript:edit_plano(' . $value_plano_acao["id"] . ', ' . $value["avaliacao"]["id"] . ',2);"><i class="fa fa-pencil-square-o fa-2x"></i></button></td>
                                <td><button type="button" class="btn btn-link" onclick="javascript:remover_plano(' . $value_plano_acao["id"] . ', ' . $value["avaliacao"]["id"] . ',2);"><i class="fa fa-trash fa-2x"></i></button></td>
                            </tr>
                    ';
                }
                echo '
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                ';
            }
            ?>
        </div>
    </div>

</div>


<div class="modal fade" id="ModelPlanoAcao" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><?php echo TITLE ?></h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Plano de Ação*</label>
                            <input class="form-control" id="txtPlanoAcao" autocomplete="off" max="100" maxlength="100" onblur="validade(this)" onkeydown="validade(this)" />
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Evidências dos Resultados/Metas*</label>
                            <input class="form-control" id="txtEvidencias" autocomplete="off" max="100" maxlength="100" onblur="validade(this)" onkeydown="validade(this)" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Matriz GUT*</label>
                            <select class="form-control" id="selGut" onblur="validade(this)">
                                <option value="">Selecione</option>
                                <option value="7 dias">7 dias</option>
                                <option value="15 dias">15 dias</option>
                                <option value="1 Mês">1 Mês</option>
                                <option value="3 Meses">3 Meses</option>
                                <option value="6 Meses">6 Meses</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label>Participantes/Área</label>
                            <input class="form-control" id="txtParticipante" autocomplete="off" max="100" maxlength="100" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                <button id="btnSalvar" type="button" class="btn btn-primary" ><span class="glyphicon glyphicon-save"></span>Salvar</button>
            </div>
        </div>
    </div>
</div>


<script src="<?php echo WEBFILES ?>js/pdi.js?<?php echo filemtime(getenv("DOCUMENT_ROOT") . "/webfiles/js/pdi.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime(getenv("DOCUMENT_ROOT") . "/webfiles/js/scripts.js"); ?>"></script>
