

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header">Menu</h1>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add" class="btn btn-default page-header" >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
            </button>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel-body">
                <div id="tree">
                    <?php print_r($view_menu); ?>
                </div>
            </div>
        </div>
        <!-- /.panel -->
    </div>


    <!-- /.col-lg-12 -->
</div>


<script src="<?php echo WEBFILES ?>js/menu.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>
<script src="<?php echo WEBFILES ?>js/jquery.tree.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#tree').tree({
            collapsible: true,
            dnd: false,
            onCheck: {
                node: 'expand'
            },
            onUncheck: {
                node: 'collapse'
            },
        });
        $('#tree').tree('expand', $('#teste'));
    });
</script>