<link href="<?php echo WEBFILES ?>css/parametros.css" rel="stylesheet" type="text/css">
<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">Parâmetros</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="save" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Título</label>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtTitle" id="txtTitle" maxlength="50" value="<?php echo $view_parametros["title"]; ?>" required>
                        </div>
                        <div class="form-group">
                            <label>Url Sigep</label>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtUrl" id="txtUrl" maxlength="50" value="<?php echo $view_parametros["url"]; ?>" type="url" required>
                        </div>
                        <div class="form-group">
                            <label>Url Portal Clientes</label>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtUrlPortal" id="txtUrlPortal" maxlength="50" value="<?php echo $view_parametros["url_portal"]; ?>" type="url" required>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                E-mail
                            </div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label>E-mail</label>
                                    <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtEmail" id="txtEmail" maxlength="100" value="<?php echo $view_parametros["notify_email"]; ?>" type="email" required>
                                    <label>Servidor</label>
                                    <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtServidor" id="txtServidor" maxlength="100" value="<?php echo $view_parametros["notify_server"]; ?>" required>
                                    <label>Porta</label>
                                    <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtPorta" id="txtPorta" maxlength="11" value="<?php echo $view_parametros["notify_port"]; ?>" type="number" required>
                                    <label>Senha</label>
                                    <input type="password" class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtPassword" id="txtPassword" value="<?php echo $view_parametros["notify_password"]; ?>" maxlength="100" required>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="<?php echo WEBFILES ?>js/parametros.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>