<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header">Habilidades (Pesos)</h1>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
            </button>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">

            <!-- /.panel-heading -->
            <!--<div class="panel-body">-->
            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="indicadores_quali_peso">
                    <thead>
                        <tr>
                            <th>Indicador</th>
                            <th>Peso 1</th>
                            <th>Intermediário 1</th>
                            <th>Peso 2</th>
                            <th>Intermediário 2</th>
                            <th>Peso 3</th>
                            <th>Intermediário 3</th>
                            <th>Peso 4</th>
                            <th style="width: 7%">Situação</th>
                            <th style="width: 5%"></th>
                            <th style="width: 5%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_indicadores_quali_peso as $un => $t) {

                            echo '
                                    <tr>
                                        <td>' . $t["indicador_quali"] . '</td>
                                        <td>' . $t["peso1"] . '</td>
                                        <td>' . $t["inter1"] . '</td>
                                        <td>' . $t["peso2"] . '</td>
                                        <td>' . $t["inter2"] . '</td>
                                        <td>' . $t["peso3"] . '</td>
                                        <td>' . $t["inter3"] . '</td>
                                        <td>' . $t["peso4"] . '</td>
                                        <td>' . $t["status"] . '</td>
                                        <td><a href="#" onclick="javascript:edita(' . $t["id"] . ');"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                                        <td><a href="#" onclick="javascript:remove(' . $t["id"] . ');"><i class="fa fa-remove fa-2x"></i></a></td>
                                    </tr>
                             ';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo WEBFILES ?>js/indicadores_quali_peso.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/indicadores_quali_peso.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>