<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">Jornada de Trabalho</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="edit" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
        </div>
        <input type="hidden" name="txtID" id="txtID" value="<?php echo $view_jornada_trabalho["id"] ?>" >
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6">
                        <div class="col-sm-" >
                            <div class="form-group">
                                <label>Descrição*</label>
                                <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtDescricao" id="txtDescricao" maxlength="150" value="<?php echo $view_jornada_trabalho["descricao"] ?>" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="col-sm-" >
                            <div class="form-group">
                                <label>Horas*</label>
                                <input class="form-control" data-mask="00:00"  onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtHoras" id="txtHoras" maxlength="250" value="<?php echo $view_jornada_trabalho["horas"] ?>" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Situação</label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="1" >Ativo
                            </label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="0">Inativo
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/jquery.mask.min.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jquery.mask.min.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/jornada_trabalho.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jornada_trabalho.js"); ?>"></script>

<script type="text/javascript">
                                    window.onload = function () {
                                        $('#txtDescricao').focus();
                                        $('input:radio[name="radStatus"][value="<?php echo $view_jornada_trabalho["status"]; ?>"]').prop('checked', true);
                                    }
</script>