<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">Graduação das Competências</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="save" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Tipo Indicador Quantitativo*</label>
                            <select class="form-control" autocomplete="off" name="selTipoIndicador" id="selTipoIndicador" >
                                <option selected value="">Selecione</option>
                                <?php
                                foreach ($view_indicador_tipo as $key => $value) {
                                    echo '
                                        <option value="' . $value["id"] . '">' . $value["descricao"] . '</option>
                                    ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Natureza Ocupacional*</label>
                            <select class="form-control" autocomplete="off" name="selNatOcupacional" id="selNatOcupacional" >
                                <option selected value="">Selecione</option>
                                <?php
                                foreach ($view_nat_ocupacional as $key => $value) {
                                    echo '
                                        <option value="' . $value["id"] . '">' . $value["descricao"] . '</option>
                                    ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Descrição*</label>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtDescricao" id="txtDescricao" maxlength="250" required>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="<?php echo WEBFILES ?>js/indicadores_quant.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>

<script type="text/javascript">
                                window.onload = function () {
                                    $('#selTipoIndicador').focus();
                                }
</script>