<link href="<?php echo WEBFILES ?>css/orgchart.css" rel="stylesheet">
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header">Estrutura Organizacional</h1>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
            </button>
        </div>
    </div>

    <div class="row">
        <div class="container">
            <ul id="tree-data" style="display:none">
                <li>
                    Empresa<br />
                    <a href="#" onclick="javascript:adicionar(0);"><i class="fa fa-plus-circle"></i></a>
                    <?php
                    echo $view_estrutura;
                    ?>
                </li>
            </ul>
            <div id="tree-view"></div>
        </div>
    </div>
</div>

<div class="modal fade" id="ModalAdicionar" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo TITLE ?></h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label>Adicionar <label id="tipo"></label></label>
                    <input class="form-control" id="txtAdicionar" onblur="validade(this)" onkeyup="validade(this)" maxlength="50" />
                </div>
                <div class="form-group">
                    <label>Ordem <label id="tipo"></label></label>
                    <input type="number" min="1" max="99" step="1" class="form-control" id="txtOrdem" onblur="validade(this)" onkeyup="validade(this)" maxlength="2" value="1" />
                </div>
                <button type="button" class="btn btn-primary" id="save" data-dismiss="modal">Salvar</button>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo WEBFILES ?>js/estr_orgonanizacional.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/estr_orgonanizacional.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/orgchart.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/orgchart.js"); ?>"></script>


<script type="text/javascript">

                        $(document).ready(function () {
                            $("#tree-data").jOrgChart({
                                chartElement: $("#tree-view"),
                                nodeClicked: function (node) {
                                    $(node).attr("id");
                                }
                            });

                        });



</script>