
<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">Usuários - Alterar Senha</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="edit_passwd" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
            <!-- /.col-lg-12 -->
            <input type="hidden" name="txtID" id="txtID" value="<?php echo $view_user["id"]; ?>" >
        </div>
        <div class="panel panel-default">
            <!-- /.panel-heading -->
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6" >

                        <label for="basic-url">&nbsp;</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtNome" id="txtNome" maxlength="50" value="<?php echo $view_user["name"]; ?>" required>
                        </div>

                        <label for="basic-url">&nbsp;</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></span>
                            <input class="form-control" onkeyup="validade(this)" disabled onblur="validade(this)" autocomplete="off" name="txtEmail" id="txtEmail" maxlength="50" value="<?php echo $view_user["email"] ?>" required>
                        </div>

                        <label for="basic-url">&nbsp;</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
                            <input type="password" autocomplete="off" value="" required name="password" id="password" class="form-control" placeholder="Digite sua nova senha" aria-describedby="sizing-addon1">
                        </div>

                        <label for="basic-url">&nbsp;</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
                            <input type="password" autocomplete="off" value="" required name="password1" id="password1" class="form-control" placeholder="Confirme sua nova senha" aria-describedby="sizing-addon1">
                        </div>

                    </div>
                </div>
                <!--</div>  .tabs -->
            </div>

            <!-- /.panel-body -->
        </div>
    </form>
</div>
<div class="modal fade" id="loading" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo TITLE ?></h4>
            </div>
            <div class="modal-body" style="text-align: center">
                <img alt="loading" title="loading" src="<?php echo WEBFILES ?>/img/loading_1.gif" />
            </div>
        </div>
    </div>
</div>
<script src="<?php echo WEBFILES ?>js/usuarios.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>
<script src="<?php echo WEBFILES ?>js/jquery.tree.min.js"></script>