<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header">Pessoas</h1>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="pessoas_lista">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Cidade</th>
                            <th>Telefone</th>
                            <th style="width: 5%"></th>
                            <th style="width: 5%"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_pessoa as $key => $value) {
                            echo '
                                <tr>
                                    <td>' . $value["nome"] . '</td>
                                    <td>' . $value["cidade"] . '</td>
                                    <td>' . $value["fone1"] . '</td>
                                    <td><a href="#" onclick="javascript:edita(' . $value["id"] . ');"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                                    <td><a href="#" onclick="javascript:remove(' . $value["id"] . ');"><i class="fa fa-remove fa-2x"></i></a></td>
                                </tr>
                            ';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo WEBFILES ?>js/pessoa.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/pessoa.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>
