<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header"><?php echo $view_indicadores_quant["descricao"] ?></h1>
                <h3><?php echo $view_indicadores_sub["descricao"] ?></h3>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="save_negacao" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close_negacao" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
        </div>
        <input type="hidden" id="txtID" value="<?php echo $view_indicadores_quant["id"] ?>" />
        <input type="hidden" id="txtIdSub" value="<?php echo $view_indicadores_sub["id"] ?>" />
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Descrição*</label>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtDescricao" id="txtDescricao" maxlength="250" required>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="<?php echo WEBFILES ?>js/indicadores_quant_tipo.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>

<script type="text/javascript">
                                window.onload = function () {
                                    $('#txtDescricao').focus();
                                }
</script>