<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header">Clientes</h1>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="empresas_listas">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Razão Social</th>
                            <th>CPF/CNPJ</th>
                            <th>Cidade</th>
                            <th style="width: 10px;"></th>
                            <th style="width: 10px;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_clients as $un => $t) {

                            if ($t["cnpj"] == "99.999.999/9999-99" && $t["cpf"] == "999.999.999-99") {
                                $t["CIC"] = "";
                            } else {
                                if ($t["nature"] == 1 && $t["cnpj"] == "99.999.999/9999-99") {
                                    $t["CIC"] = $t["cpf"];
                                } else if ($t["nature"] == 2 && $t["cpf"] == "999.999.999-99") {
                                    $t["CIC"] = $t["cnpj"];
                                } else {
                                    $t["CIC"] = ($t["nature"] == 1 ? $t["cnpj"] : $t["cpf"]);
                                }
                            }

                            echo '
                                    <tr >
                                        <td>' . $t["name"] . '</td>
                                        <td>' . $t["social_razon"] . '</td>
                                        <td>' . $t["CIC"] . '</td>
                                        <td>' . $t["city"] . '</td>
                                        <td><a href="#" onclick="javascript:edita(' . $t["id"] . ');"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                                        <td><a href="#" onclick="javascript:remove(' . $t["id"] . ');"><i class="fa fa-remove fa-2x"></i></a></td>
                                    </tr>
                             ';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo WEBFILES ?>js/clients.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>
