<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">CBO</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="edit" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
        </div>
        <input type="hidden" name="txtID" id="txtID" value="<?php echo $view_cbo["id"] ?>" />
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Código*</label>
                            <input type="number" class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtCodigo" id="txtCodigo" value="<?php echo $view_cbo["codigo"] ?>" maxlength="15" required>
                        </div>
                    </div>
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Título*</label>
                            <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtTitulo" id="txtTitulo" value="<?php echo $view_cbo["titulo"] ?>" maxlength="150" required>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Situação</label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="1" >Ativo
                            </label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="0">Inativo
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="<?php echo WEBFILES ?>js/cbo.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/cbo.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>

<script type="text/javascript">
                                window.onload = function () {
                                    $('input:radio[name="radStatus"][value="<?php echo $view_cbo["status"]; ?>"]').prop('checked', true);
                                    $('#txtCodigo').focus();
                                }
</script>