<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12" >
            <h1 class="page-header">Funcionarios DICA</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="avaliacao_lista">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Cargo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_funcionarios as $value) {
                            echo '
                                    <tr class="tr_table" onclick="abre_dica(this)" id_funcionario="' . $value["id_funcionario"] . '">
                                        <td>' . $value["nome"] . '</td>
                                        <td>' . $value["cargo"] . '</td>
                                    </tr>
                             ';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<script src="<?php echo WEBFILES ?>js/avaliacao.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/avaliacao.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>
