<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-7" >
                <h1 class="page-header">Restrições</h1>
            </div>
            <div class="col-lg-5 botoes_menu" >

                <button type="button" id="add" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
                </button>

                <button type="button" id="edita" value="<?php echo $view_restricao["id"]; ?>" class="btn btn-default page-header " >
                    <span class="fa fa-pencil-square-o" aria-hidden="true"></span> Editar
                </button>
                <button type="button" id="remove" value="<?php echo $view_restricao["id"]; ?>" class="btn btn-default page-header " >
                    <span class="fa fa-trash" aria-hidden="true"></span> Remover
                </button>
                <button type="button" id="search" class="btn btn-default page-header " >
                    <span class="fa fa-search" aria-hidden="true"></span> Pesquisar
                </button>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="panel panel-default">
            <!-- /.panel-heading -->
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Nome</label>
                            <input autocomplete="off" class="form-control input-group-sm" readonly value="<?php echo $view_restricao["nome"]; ?>" >
<!--                            <p class="help-block">Nome abreviado do cliente para rápida consulta.</p>-->
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <?php #echo $view_pagination; ?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Dias da semana</label><br />
                            <label class="checkbox-inline">
                                <input type="checkbox" readonly <?php if ($view_restricao["seg"]) echo "checked"; ?> >Seg
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox" readonly <?php if ($view_restricao["ter"]) echo "checked"; ?> >Ter
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox" readonly <?php if ($view_restricao["qua"]) echo "checked"; ?> >Qua
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox" readonly <?php if ($view_restricao["qui"]) echo "checked"; ?> >Qui
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox" readonly <?php if ($view_restricao["sex"]) echo "checked"; ?> >Sex
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox" readonly <?php if ($view_restricao["sab"]) echo "checked"; ?> >Sáb
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox" readonly <?php if ($view_restricao["dom"]) echo "checked"; ?> >Dom
                            </label>
                        </div>
                        <div class="form-group">
                            <label>Hora início</label>
                            <input autocomplete="off" class="form-control input-group-sm" readonly value="<?php echo $view_restricao["hora_ini"]; ?>" >
                            <!--<p class="help-block">Selecionar o grupo de clientes.</p>-->
                        </div>
                        <div class="form-group">
                            <label>Hora fim</label>
                            <input autocomplete="off" class="form-control input-group-sm" readonly value="<?php echo $view_restricao["hora_fim"]; ?>" >
                            <!--<p class="help-block">Razão social do cliente.</p>-->
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="myModal2" role="dialog">
                    <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title"><?php echo TITLE ?></h4>
                            </div>
                            <div class="modal-body">
                                <div class="form-group input-group">
                                    <input type="text" class="form-control" name="txtSearch" id="txtSearch" onkeyup="showResult2(this.value)" onblur="teste()">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button"><i class="fa fa-search"></i>
                                        </button>
                                    </span>

                                </div>
                                <div id="livesearch" style="position: absolute; background-color: #f5f5f5;  "></div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12" >
                        <?php echo $view_pagination; ?>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
    </form>
</div>
<script src="<?php echo WEBFILES ?>js/restricoes.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>
<script type="text/javascript">
                                        function showResult2(str) {
                                            if (str.length == 0) {
                                                document.getElementById("livesearch").innerHTML = "";
                                                document.getElementById("livesearch").style.border = "0px";
                                                return;
                                            }

                                            $.ajax({
                                                url: '/restricoes/search',
                                                type: 'post',
                                                dataType: 'html',
                                                data: {
                                                    'search': $('#txtSearch').val(),
                                                }
                                            }).done(function (data) {
                                                resultado = data;
                                                document.getElementById("livesearch").innerHTML = resultado;
                                                document.getElementById("livesearch").style.border = "1px solid #A5ACB2";

                                            });
                                        }
                                        function teste() {
//        document.getElementById("livesearch").innerHTML = "";
//        document.getElementById("livesearch").style.border = "0px";
                                        }
</script>