<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">Grupo de Desempenho Profissional</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="edit" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
        </div>
        <input type="hidden" name="txtID" id="txtID" value="<?php echo $view_gdp["id"] ?>" >
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6">
                        <div class="col-sm-" >
                            <div class="form-group">
                                <label>Descrição*</label>
                                <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtDescricao" id="txtDescricao" value="<?php echo $view_gdp["descricao"] ?>" maxlength="250" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="col-sm-" >
                            <div class="form-group">
                                <label>Classificação*</label>
                                <input class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" name="txtClassificacao" id="txtClassificacao" value="<?php echo $view_gdp["classificacao"] ?>" maxlength="1" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Percentual Mínimo*</label>
                            <input class="form-control" placeholder="0,00" autocomplete="off" name="txtPerc_Min" id="txtPerc_Min" value="<?php echo $view_gdp["perc_min"] ?>" maxlength="6">
                        </div>
                    </div>
                    <div class="col-sm-6" >
                        <div class="form-group">
                            <label>Percentual Máximo*</label>
                            <input class="form-control" placeholder="0,00" autocomplete="off" name="txtPerc_Max" id="txtPerc_Max" value="<?php echo $view_gdp["perc_max"] ?>" maxlength="6">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Situação</label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="1" >Ativo
                            </label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="0">Inativo
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="<?php echo WEBFILES ?>js/gdp.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/gdp.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/jquery.mask.min.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jquery.mask.min.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/jquery.maskMoney.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jquery.maskMoney.js"); ?>"></script>

<script type="text/javascript">
                                    window.onload = function () {
                                        $('input:radio[name="radStatus"][value="<?php echo $view_gdp["status"]; ?>"]').prop('checked', true);
                                        $('#txtDescricao').focus();
                                        $('#txtPerc_Min').maskMoney({showSymbol: true, symbol: "", decimal: ",", thousands: ".", precision: 3});
                                        $('#txtPerc_Max').maskMoney({showSymbol: true, symbol: "", decimal: ",", thousands: ".", precision: 3});
                                    }
</script>