

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header">Usuários</h1>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add" class="btn btn-default page-header" >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar

            </button>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <!-- /.panel-heading -->
            <!--<div class="panel-body">-->
            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="tarefas">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Situação</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_user as $un => $t) {
                            if ($t["status"] == 1) {
                                $t["status"] = "Ativo";
                            } else {
                                $t["status"] = "Inativo";
                            }

                            if ($t["id"] == $_SESSION["user_id"]) {
                                echo '
                                    <tr >
                                        <td>' . $t["id"] . '</td>
                                        <td>' . $t["name"] . '</td>
                                        <td>' . $t["email"] . '</td>
                                        <td>' . $t["status"] . '</td>
                                        <td><a href="javascript:edita(' . $t["id"] . ');"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                                        <td></td>
                                    </tr>
                             ';
                            } else {
                                echo '
                                    <tr >
                                        <td>' . $t["id"] . '</td>
                                        <td>' . $t["name"] . '</td>
                                        <td>' . $t["email"] . '</td>
                                        <td>' . $t["status"] . '</td>
                                        <td><a href="javascript:edita(' . $t["id"] . ');"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                                        <td><a href="javascript:remove(' . $t["id"] . ');"><i class="fa fa-remove fa-2x"></i></a></td>
                                    </tr>
                             ';
                            }
                        }
                        ?>

                    </tbody>
                </table>

            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>


    <!-- /.col-lg-12 -->
</div>


<script src="<?php echo WEBFILES ?>js/usuarios.js"></script>