<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-10" >
            <h1 class="page-header">Usuários Clientes</h1>
        </div>
        <div class="col-lg-2 botoes_menu" >
            <button type="button" id="add" class="btn btn-default page-header " >
                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Adicionar
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="dataTable_wrapper">
                <table width="100%" class="table table-striped table-bordered table-hover" id="usuarios_clientes_listas">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th class="text-center" style="width: 70px;">Situação</th>
                            <th style="width: 10px;"></th>
                            <th style="width: 10px;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($view_clients_users as $un => $t) {

                            echo '
                                    <tr >
                                        <td>' . $t["name"] . '</td>
                                        <td>' . $t["email"] . '</td>
                                        <td class="text-center">' . $t["situacao"] . '</td>
                                        <td class="text-center"><a href="#" onclick="javascript:edita(' . $t["id"] . ');"><i class="fa fa-pencil-square-o fa-2x"></i></a></td>
                                        <td class="text-center"><a href="#" onclick="javascript:remove(' . $t["id"] . ');"><i class="fa fa-remove fa-2x"></i></a></td>
                                    </tr>
                             ';
                        }
                        ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo WEBFILES ?>js/scripts.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/scripts.js"); ?>"></script>
<script src="<?php echo WEBFILES ?>js/clients_users.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/clients_users.js"); ?>"></script>
