<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-12" >
                <h1 class="page-header">Comparativos GDP</h1>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-3">
                        <label>Data inicial</label>
                        <div class="form-group input-group">
                            <input autocomplete="off" onkeyup="validade(this)" onblur="validade(this)" class="form-control input-group-sm data" maxlength="10" id="txtDataIni" data-mask="00/00/0000" placeholder="00/00/0000"  value="<?php echo "01/01" . date("/Y") ?>" >
                            <span class="input-group-btn">
                                <button class="btn btn-default" id="btnDataIni" name="btnDataIni" type="button"><i class="fa fa-calendar"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <label>Data final</label>
                        <div class="form-group input-group">
                            <input autocomplete="off" onkeyup="validade(this)" onblur="validade(this)" class="form-control input-group-sm data" maxlength="10" id="txtDataFim" data-mask="00/00/0000" placeholder="00/00/0000" value="<?php echo date("d/m/Y") ?>" >
                            <span class="input-group-btn">
                                <button class="btn btn-default" id="btnDataFim" name="btnDataFim" type="button"><i class="fa fa-calendar"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <label> .</label>
                        <div class="form-group input-group">
                            <button type="button" id="btnGerarComparativo" class="btn btn-default " >
                                <span class="fa fa-list-alt" aria-hidden="true"></span> Gerar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-lg-6">
                        <!--<canvas id="qualiXquant" ></canvas>-->
                        <div id="qualiXquant" style="height: 500px"></div>
                    </div>
                    <div class="col-lg-6">
                        <div id="gdpXescolaridade" style="height: 500px"></div>
                        <!--<canvas id="gdpXescolaridade" ></canvas>-->
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div id="gdpXsexo" style="height: 500px"></div>
                    </div>
                    <div class="col-lg-6">
                        <div id="gdpXsalario" style="height: 500px"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div id="gdpXfaixaIdade" style="height: 500px"></div>
                    </div>
                    <div class="col-lg-6">
                        <div id="gdpXarea" style="height: 500px"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div id="gdpXcargo" style="height: 500px"></div>
                    </div>
                    <div class="col-lg-6">
                        <div id="gdpXnat" style="height: 500px"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="dataTable_wrapper" style="height: 500px">
                            <table id="gdpXfuncionario" width="100%" class="table table-striped table-bordered table-hover" style="cursor:pointer">
                                <thead>
                                    <tr>
                                        <th class="text-center">Área</th>
                                        <th class="text-center">Colaborador</th>
                                        <th class="text-center">Data</th>
                                        <th class="text-center">GDP</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div id="resultado"></div>

    </form>
</div>


<script src="<?php echo WEBFILES ?>js/avaliacao.js"></script>
<script src="<?php echo WEBFILES ?>js/jquery.mask.min.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


<script type="text/javascript">
                                $(function () {
                                    $(".data").datepicker({
                                        changeMonth: true,
                                        changeYear: true,
                                        dateFormat: 'dd/mm/yy',
                                        dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
                                        dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
                                        dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
                                        monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
                                        monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
                                    });
                                });



</script>
