<div id="page-wrapper">
    <form class="frmSave" id="frmSave" autocomplete="off" >
        <div class="row">
            <div class="col-lg-8" >
                <h1 class="page-header">Montagem Estrutua Organizacional</h1>
            </div>
            <div class="col-lg-4 botoes_menu" >
                <button type="button" id="edit" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Salvar
                </button>

                <button type="button" id="close" class="btn btn-default page-header " >
                    <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Cancelar
                </button>
            </div>
        </div>
        <input type="hidden" name="txtID" id="txtID" value="<?php echo $view_mont_estru_org["id"] ?>" >
        <div class="panel panel-default">
            <div class="panel-body" >
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Estrutura Organizacional*</label>
                            <select class="form-control" autocomplete="off" name="selEstruturaOrg" id="selEstruturaOrg" >
                                <option selected value="">Selecione</option>
                                <?php
                                foreach ($view_estrutura as $key => $value) {
                                    echo '
                                        <option value="' . $value["id"] . '">' . $value["descricao"] . '</option>
                                    ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Classificação Organizacional*</label>
                            <select class="form-control" autocomplete="off" name="selClassOrg" id="selClassOrg" >
                                <option selected value="">Selecione</option>
                                <?php
                                foreach ($view_classificacao as $key => $value) {
                                    echo '
                                        <option value="' . $value["id"] . '">' . $value["descricao"] . '</option>
                                    ';
                                }
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="col-sm-" >
                            <div class="form-group">
                                <label>Posição*</label>
                                <input type="number" class="form-control" onkeyup="validade(this)" onblur="validade(this)" autocomplete="off" value="<?php echo $view_mont_estru_org["posicao"] ?>" name="txtPosicao" id="txtPosicao" maxlength="3" required>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Situação</label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="1" >Ativo
                            </label>
                            <label class="radio-inline">
                                <input type="radio"  name="radStatus" id="radStatus" value="0">Inativo
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>



<script src="<?php echo WEBFILES ?>js/mont_estru_org.js"></script>
<script src="<?php echo WEBFILES ?>js/scripts.js"></script>

<script type="text/javascript">
                                    window.onload = function () {
                                        $("#selEstruturaOrg").val("<?php echo $view_mont_estru_org["id_estrutura_org"] ?>").change();
                                        $("#selClassOrg").val("<?php echo $view_mont_estru_org["id_class_org"] ?>").change();
                                        $('input:radio[name="radStatus"][value="<?php echo $view_mont_estru_org["status"]; ?>"]').prop('checked', true);
                                        $('#selEstruturaOrg').focus();
                                    }
</script>