<!DOCTYPE html>
<html lang="pt-BR">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="<?php echo WEBFILES . "img/icon.jpg"; ?>" />
        <title><?php echo TITLE ?></title>

        <link href="<?php echo WEBFILES ?>css/bootstrap.min.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/bootstrap.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo WEBFILES ?>css/jquery-ui.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/jquery-ui.css"); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo WEBFILES ?>css/metisMenu.min.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/metisMenu.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo WEBFILES ?>css/sb-admin-2.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/sb-admin-2.css"); ?>" rel="stylesheet">
        <link href="<?php echo WEBFILES ?>css/font-awesome.min.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/font-awesome.min.css"); ?>" rel="stylesheet" type="text/css">
        <link href="<?php echo WEBFILES ?>css/dataTables.bootstrap.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/dataTables.bootstrap.css"); ?>" rel="stylesheet">
        <link href="<?php echo WEBFILES ?>css/dataTables.responsive.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/dataTables.responsive.css"); ?>" rel="stylesheet">
        <link href="<?php echo WEBFILES ?>css/aba.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/aba.css"); ?>" rel="stylesheet">
        <link href="<?php echo WEBFILES ?>css/jquery.tree.min.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/jquery.tree.min.css"); ?>" rel="stylesheet">
        <link href="<?php echo WEBFILES ?>css/bootstrap-select.css?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/css/bootstrap-select.css"); ?>" rel="stylesheet">

        <!--[if lt IE 9]>
            <script src="<?php echo WEBFILES ?>js/html5shiv.js"></script>
            <script src="<?php echo WEBFILES ?>js/respond.min.js"></script>
        <![endif]-->
        <script src="<?php echo WEBFILES ?>js/jquery-1.12.0.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jquery-1.12.0.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/jquery-ui.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jquery-ui.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/bootstrap.min.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/bootstrap.min.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/metisMenu.min.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/metisMenu.min.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/sb-admin-2.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/sb-admin-2.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/aba.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/aba.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/jquery.dataTables.min.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jquery.dataTables.min.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/dataTables.bootstrap.min.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/dataTables.bootstrap.min.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/jquery.redirect.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/jquery.redirect.js"); ?>"></script>
        <script src="<?php echo WEBFILES ?>js/bootstrap-select.js?<?php echo filemtime($_SERVER["DOCUMENT_ROOT"] . "/webfiles/js/bootstrap-select.js"); ?>"></script>

    </head>

    <body>

        <div id="wrapper">