<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="<?php echo WEBFILES ?>img/icon.jpg" />
        <title><?php echo TITLE ?></title>
        <link href="<?php echo WEBFILES ?>css/bootstrap.min.css" rel="stylesheet">
        <script src="<?php echo WEBFILES ?>js/jquery.min.js"></script>
        <script src="<?php echo WEBFILES ?>js/bootstrap.min.js"></script>
        <!--[if lt IE 9]><script src="<?php echo WEBFILES ?>js/ie8-responsive-file-warning.js"></script><![endif]-->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="<?php echo WEBFILES ?>js/html5shiv.min.js"></script>
          <script src="<?php echo WEBFILES ?>js/respond.min.js"></script>
        <![endif]-->
        <script src="<?php echo WEBFILES ?>js/ie10-viewport-bug-workaround.js"></script>
        <script src="<?php echo WEBFILES ?>js/ie-emulation-modes-warning.js"></script>
    </head>
    <body>
        <div class="navbar-wrapper">
            <div class="container">
                <nav class="navbar navbar-static-top">
                    <div class="container"></div>
                </nav>
            </div>
        </div>
        <link href="<?php echo WEBFILES ?>css/login.css" rel="stylesheet">
        <div class="container">
            <div id="main" class="contato-mail">
                <div id="logo" class="logo">
                    <img src="<?php echo WEBFILES ?>/img/logo.jpg" />
                </div>
                <div class="form-contato" id="form-contato">
                    <form class="frmLogin" id="frmLogin" >
                        <label for="basic-url">&nbsp;</label>
                        <!--E-mail-->
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></span>
                            <input type="text" autocomplete="off" required name="login" id="login" class="form-control" placeholder="Seu Login" aria-describedby="sizing-addon1">
                        </div>
                        <!--Senha-->
                        <label for="basic-url">&nbsp;</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-addon" id="sizing-addon1"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span></span>
                            <input type="password" autocomplete="off" required name="password" id="password" class="form-control" placeholder="Sua Senha" aria-describedby="sizing-addon1">
                        </div>
                        <label for="basic-url">&nbsp;</label>
                        <div >
                            <button type="submit" id="entra" class="btn btn-default btn-lg" data-loading-text="Carregando ...">
                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Entrar
                            </button>
                            <button type="button" id="recover_password" class="btn btn-default btn-lg" data-loading-text="Carregando ...">
                                <span class="glyphicon glyphicon-asterisk" aria-hidden="true"></span> Recuperar senha
                            </button>
                        </div>
                        <div class="modal fade" id="myModal2" role="dialog">
                            <div class="modal-dialog">
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        <h4 class="modal-title"><?php echo TITLE ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>Dados de entrada inválidos!</p>
                                        <p>Tente novamente</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <script src="<?php echo WEBFILES ?>js/formulario.js"></script>
        <script type="text/javascript">
            window.onload = function () {
                $('#login').focus();
            }
        </script>
    </body>
</html>